apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubclust-89bd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubclust-89bd"
  template:
    metadata:
      labels:
        app: "kubclust-89bd"
    spec:
      containers:
        - name: "kubclust-89bd"
          image: "conregkub.azurecr.io/kubclust"
          ports:
          - containerPort: 80